CXX        = g++ -std=c++0x
#CXX        = g++
CXXFLAGS   = -Wall -g
INCS      = `root-config --cflags` -I.
LIBS      = `root-config --libs` 

Dummy.exe: Dummy.cxx  
	$(CXX) $(CXXFLAGS) $< -o $@ $(INCS) $(LIBS)

Dict.o : Dict.cxx 
		$(CC) $(CCFLAGS) -c $< $(INCS) $(LIBS) 

Dict.cxx : Dummy.cxx 
		rootcint -f $@ -c $<+ 

clean : 
	rm -f Dummy.exe Dict.cxx *.o *.so *.d
