#CC        = /afs/cern.ch/sw/lcg/external/gcc/4.3.5/x86_64-slc5-gcc34-opt/bin/x86_64-unknown-linux-gnu-gcc
#CC        = /afs/cern.ch/sw/lcg/external/gcc/4.3.2/x86_64/bin/g++
CXX        = /usr/bin/g++
#Enable warnings and debugging info
CXXFLAGS   = -Wall -g
INCS      = `root-config --cflags` -I.
LIBS      = `root-config --libs` -lRooFit -lRooFitCore -lRooStats

WAnalysisHip : WAnalysisHip.cc WAnalysisTool.o FitResult.o 
	$(CXX) $(CXXFLAGS) $< WAnalysisTool.o FitResult.o $(INCS) $(LIBS) -o $@

FitResult.o : FitResult.cc
	$(CXX) $(CXXFLAGS) -c $< $(INCS) $(LIBS)

WAnalysisTool.o : WAnalysisTool.cc WAnalysisTool.h
	$(CXX) $(CXXFLAGS) -c $< $(INCS) $(LIBS)

clean : 
	rm -f WAnalysisHip FitResult.o WAnalysisTool.o 
